create extension if not exists pgcrypto;
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,email text not null,created_at timestamptz not null default now());
create table if not exists public.stories(id uuid primary key default gen_random_uuid(),name text,email text not null,country text,phone text,story text not null,photo_path text,identity_private boolean not null default false,permission boolean not null default false,status text not null default 'new' check(status in ('new','reviewed','selected','archived')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists stories_status_idx on public.stories(status);
create index if not exists stories_created_at_idx on public.stories(created_at desc);
create or replace function public.is_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()); $$;
revoke all on function public.is_admin() from public; grant execute on function public.is_admin() to anon,authenticated;
alter table public.admin_users enable row level security; alter table public.stories enable row level security;
drop policy if exists "Public can submit stories" on public.stories;
create policy "Public can submit stories" on public.stories for insert to anon,authenticated with check(permission=true and length(trim(story)) between 20 and 20000 and length(email)<=320);
drop policy if exists "Admins can read stories" on public.stories;
create policy "Admins can read stories" on public.stories for select to authenticated using(public.is_admin());
drop policy if exists "Admins can update stories" on public.stories;
create policy "Admins can update stories" on public.stories for update to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists "Admins can delete stories" on public.stories;
create policy "Admins can delete stories" on public.stories for delete to authenticated using(public.is_admin());
insert into storage.buckets(id,name,public) values('story-photos','story-photos',false) on conflict(id) do update set public=false;
drop policy if exists "Public may upload story photos" on storage.objects;
create policy "Public may upload story photos" on storage.objects for insert to anon,authenticated with check(bucket_id='story-photos' and storage.extension(name) in ('jpg','jpeg','png','webp','gif'));
drop policy if exists "Admins may view story photos" on storage.objects;
create policy "Admins may view story photos" on storage.objects for select to authenticated using(bucket_id='story-photos' and public.is_admin());
drop policy if exists "Admins may delete story photos" on storage.objects;
create policy "Admins may delete story photos" on storage.objects for delete to authenticated using(bucket_id='story-photos' and public.is_admin());
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists stories_set_updated_at on public.stories;
create trigger stories_set_updated_at before update on public.stories for each row execute function public.set_updated_at();